SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PWR_DISPLAY_TIME = 2500

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_VELOCITY = 20

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 200

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

PLAYER_SHIELD = 0

SHOT_RADIUS = 5

POWERUP_RADIUS = 2

accumulated_dt = 0
SHIELDS_USED = 0
KILLS = 0
TOTAL_SHOTS = 0
TOTAL_POWERUPS = 0
TIME_PLAYED = 0